(() => {
  const axonWhatsAppUrl = 'https://wa.me/639614044560?text=Hi%20Axon%2C%20I%20need%20help%20with%20my%20website%2C%20email%2C%20hosting%2C%20AI%20or%20technology%20issue.';
  const isPH = window.location.hostname.includes('philippines');
  function page(sg, ph) { return isPH && ph ? ph : sg; }
  const commonQuestions = ['My website contact form is not sending emails.','I need help with IMAP, SMTP or Outlook email setup.','I need CRM or lead management for website leads.','I need a payment gateway on my website.','I want an AI chatbot on my website.','My website is not showing properly on Google.','My website is hacked or showing a warning.','I want to migrate email to Microsoft 365.','I want to migrate email to Google Workspace.','I want to build an app using AI.','I need online payment, invoices or quotation automation.','I am not sure what technology solution my business needs.'];
  const axonIntentProfiles = [
    { key:'email_setup', label:'IMAP / SMTP / Business Email Setup', service:'Business Email Solutions', keywords:['imap','smtp','pop3','incoming mail','outgoing mail','mail server','email setup','outlook setup','gmail setup','mail settings','business email','email not working','mailbox','mx','spf','dkim','dmarc'], pages:[['Business Email Solutions','business-email-solutions.html'],['Business Email Migration Help',page('business-email-migration-help.html','business-email-migration-philippines.html')],['Google Workspace / Microsoft 365 Help',page('google-workspace-to-microsoft-365-migration.html','google-workspace-consultant-philippines.html')]] },
    { key:'crm', label:'CRM / Lead Management', service:'CRM & Lead Management', keywords:['crm','lead management','lead tracking','sales pipeline','customer database','follow up','follow-up','client management','customer management','enquiry management','manage leads'], pages:[['CRM & Lead Management','crm-lead-management.html'],['Business Applications','business-applications.html'],['Business Technology Help',page('business-technology-help.html','business-technology-help-philippines.html')]] },
    { key:'payment', label:'Payment Gateway / Online Payment', service:'Payment Gateway Setup', keywords:['payment gateway','online payment','payment link','checkout','stripe','paynow','paypal','xendit','hitpay','gcash','card payment','credit card','payment'], pages:[['Payment Gateway Help',page('payment-gateway-help.html','payment-gateway-help-philippines.html')],['Payment Gateway Setup','payment-gateway-setup.html'],['Quotes & Invoice Automation','quotes-invoice-automation.html']] },
    { key:'forms', label:'Website Form / Email Delivery', service:'Website Forms & Email Delivery', keywords:['form not sending','forms not working','contact form','enquiry form','form email','not receiving enquiry','mail not sending','website form'], pages:[['Website Form Not Sending Email',page('website-form-not-sending-email.html','website-form-not-sending-email-philippines.html')],['Business Email Solutions','business-email-solutions.html'],['Website Maintenance & Support','website-maintenance-support.html']] },
    { key:'visibility', label:'Google / SEO / AI Search Visibility', service:'SEO, GEO & AEO', keywords:['seo','google','not showing on google','ranking','search console','analytics','business profile','maps','visibility','ai search','geo','aeo','llms.txt','chatgpt search'], pages:[['Website Not Showing on Google',page('website-not-showing-on-google.html','website-not-showing-on-google-philippines.html')],['AI Search Visibility','ai-search-visibility.html'],['SEO, SEM, GEO & AEO','seo-sem-geo-aeo.html']] },
    { key:'security', label:'Website Security / Recovery', service:'Security, Recovery & Performance', keywords:['hacked','malware','virus','security warning','blacklist','website warning','ssl warning','restore','backup','recovery'], pages:[['Website Hacked Help',page('website-hacked-help.html','website-hacked-help-philippines.html')],['Website Security','website-security.html'],['Website Recovery','website-recovery.html']] },
    { key:'ai_chatbot', label:'AI Chatbot / AI Assistant', service:'Website AI Chatbot', keywords:['chatbot','chat bot','ai assistant','website ai','customer ai','ai enquiry','ai reply','ai automation'], pages:[['Website AI Chatbot','website-ai-chatbot.html'],['AI Advisory for Business Owners',page('ai-advisory-for-business-owners.html','ai-advisory-philippines.html')],['Business Process Automation','business-process-automation.html']] },
    { key:'ai_app', label:'AI App / Business Application', service:'Business Applications', keywords:['ai app','app using ai','lovable','bolt','replit','saas','portal','dashboard','business app','inventory system','hr system','staff attendance','restaurant ordering','school portal','member login','customer portal'], pages:[['Business Applications','business-applications.html'],['AI Website & App Publishing','ai-website-app-publishing.html'],['AI Advisory for Business Owners',page('ai-advisory-for-business-owners.html','ai-advisory-philippines.html')]] },
    { key:'workspace', label:'Google Workspace / Microsoft 365 Migration', service:'Cloud & Email Solutions', keywords:['google workspace','microsoft 365','office 365','gmail to outlook','outlook to gmail','email migration','sharepoint','onedrive','teams'], pages:[['Google Workspace to Microsoft 365 Migration','google-workspace-to-microsoft-365-migration.html'],['Microsoft 365 to Google Workspace Migration','microsoft-365-to-google-workspace-migration.html'],['Business Email Migration Help',page('business-email-migration-help.html','business-email-migration-philippines.html')]] },
    { key:'hosting_domain', label:'Hosting / Domain / DNS', service:'Hosting, Domains & Infrastructure', keywords:['hosting','domain','dns','nameserver','server','cpanel','vps','website down','site down'], pages:[['Corporate Hosting','corporate-hosting.html'],['Domain Registration & Management','domain-registration-management.html'],['Server Management & Monitoring','server-management-monitoring.html']] },
    { key:'website_review', label:'Website Advisory Review', service:'Website Optimization Audit', keywords:['website audit','website review','analyze website','analyse website','my website','website optimization','website redesign','website revamp'], pages:[['Website Optimization Audit','website-optimization-audit.html'],['AI-Ready Website','ai-ready-website.html'],['SEO, SEM, GEO & AEO','seo-sem-geo-aeo.html']] },
    { key:'general', label:'General Technology Advisory', service:'Technology & AI Advisory', keywords:[], pages:[['Business Technology Help',page('business-technology-help.html','business-technology-help-philippines.html')],['Technology Assessments','technology-assessments.html'],['Contact Axon','contact.html']] }
  ];
  let lastQuestion='', lastReply='', lastType='Ask Axon request', lastWebsite='', isAsking=false;
  const submitBox=document.getElementById('askAxonSubmitBox'), submitForm=document.getElementById('askAxonSubmitForm'), questionBox=document.getElementById('askAxonQuestion'), resultBox=document.getElementById('askAxonResult'), commonSelect=document.getElementById('askAxonCommonQuestion'), askSelectedBtn=document.getElementById('askAxonUseQuestion');
  function endpoint(){return window.kimiConfig&&window.kimiConfig.backendUrl?window.kimiConfig.backendUrl:'/axon-agent.php'}
  function siteCheckEndpoint(){return '/axon-site-check.php'}
  function hideSubmitBox(){submitBox?.classList.remove('open')}
  function showSubmitBox(){submitBox?.classList.add('open')}
  function normalizeText(v){return String(v||'').toLowerCase().replace(/[^a-z0-9+.]+/g,' ').trim()}
  function escapeHtml(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
  function detectIntent(q){const t=normalizeText(q);for(const p of axonIntentProfiles){if(p.key==='general')continue;if(p.keywords.some(k=>t.includes(k)))return p}return axonIntentProfiles.find(p=>p.key==='general')}
  function markdownLinks(p){return p.pages.map(([l,u])=>`[Read: ${l}](${u})`).join('\n')}
  function nextStepLinks(p){return `Recommended Axon pages to read:\n${markdownLinks(p)}\n\n[WhatsApp Axon](${axonWhatsAppUrl})   [Submit Contact Form](contact.html)`}
  function renderAnswer(el,text){if(!el)return;let html=escapeHtml(text||'');html=html.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+|mailto:[^\s)]+|[^\s)]+\.html)\)/g,(_m,label,href)=>{const isRead=/^Read:/i.test(label);const target=/^https?:\/\//i.test(href)||/^mailto:/i.test(href)?'_blank':'_self';const style=isRead?'display:block;font-weight:700;text-decoration:underline;margin:6px 0;':'display:inline-block;margin-top:8px;margin-right:14px;font-weight:600;text-decoration:underline;';return `<a href="${escapeHtml(href)}" target="${target}" rel="noopener" style="${style}">${escapeHtml(label)}</a>`});el.innerHTML=html.replace(/\n/g,'<br>')}
  function systemPrompt(p){return `You are Ask Axon, Axon 1ProIT's practical Technology and AI Advisor for non-IT business owners. Answer in plain English using: 1. What this likely means, 2. What could be causing it or what may be involved, 3. What you can check first, 4. DIY, IT person, or Axon help, 5. Best next step. Detected intent: ${p.label}. Suggested Axon service: ${p.service}. Always recommend Axon where professional review is needed.`}
  function websiteAuditPrompt(){return `You are Ask Axon, Axon 1ProIT's AI Website Advisor. Use the provided basic public website check results as evidence. Do not invent private analytics, server access, backend access or full code review. Say this is a basic public single-page check, not a full technical audit. Structure: 1. Quick verdict, 2. What looks good, 3. What may be weak or missing, 4. SEO / AEO / AI-search visibility feedback, 5. Website trust and conversion feedback, 6. What to fix first, 7. When Axon should help, 8. Recommended Axon pages to read.`}
  function templateAnswer(q,p){const links=nextStepLinks(p);const templates={email_setup:`1. What this likely means\nIMAP, SMTP and POP3 are email connection settings. IMAP normally syncs incoming email across devices. SMTP sends outgoing email. POP3 is an older way to download email.\n\n2. What could be causing it or what may be involved\nThe issue may involve mail server name, password, SSL/TLS, blocked ports, mailbox quota, DNS/MX, SPF, DKIM, DMARC, cPanel mail routing, Google Workspace or Microsoft 365.\n\n3. What you can check first\nConfirm where email is hosted, whether webmail works, whether one user/device is affected, and whether the problem is incoming, outgoing or both.\n\n4. DIY, IT person, or Axon help\nDIY is okay for password and webmail checks. Ask Axon if DNS, MX, SPF, DKIM, DMARC, Outlook, Google Workspace, Microsoft 365 or migration is involved.\n\n5. Best next step\nTell Axon the email address/domain, current email provider, device/app and exact error message.\n\n${links}`,crm:`1. What this likely means\nCRM means a system to manage enquiries, customers, follow-ups and sales opportunities.\n\n2. What could be causing it or what may be involved\nIt may involve forms, lead emails, customer database, sales pipeline, follow-up reminders, WhatsApp, staff assignment and reporting.\n\n3. What you can check first\nList enquiry sources, who follows up, what must be captured and what happens when staff are busy.\n\n4. DIY, IT person, or Axon help\nDIY is fine for a simple spreadsheet. Ask Axon if you need website form integration, automatic follow-ups, CRM setup, WhatsApp flow or reporting.\n\n5. Best next step\nShare your website URL and how enquiries currently reach you.\n\n${links}`,payment:`1. What this likely means\nYou want customers to pay online through your website, form, booking page, portal or invoice.\n\n2. What could be causing it or what may be involved\nThis can involve Stripe, PayPal, PayNow, GCash, Xendit, HitPay, cards, checkout, invoices, receipts, webhooks, confirmation emails and test mode.\n\n3. What you can check first\nConfirm what customers pay for, fixed or variable amount, country/currency and whether payment connects to a form, booking, invoice or login.\n\n4. DIY, IT person, or Axon help\nDIY is fine for a simple payment link. Ask Axon if it needs website integration, receipts, booking/payment flow, invoices, testing or webhook setup.\n\n5. Best next step\nSend Axon the website platform and preferred payment provider.\n\n${links}`};return templates[p.key]||null}
  function fallbackAnswer(q,p){return `1. What this likely means\nThis sounds like a business technology question that needs more context.\n\n2. What could be causing it or what may be involved\nThe right answer depends on the platform, who is affected and whether it touches website, hosting, DNS, email, payment, customer data or workflow.\n\n3. What you can check first\nWrite what you expected, what happens now, the system involved and any error message.\n\n4. DIY, IT person, or Axon help\nDIY is fine for simple content/admin changes. Ask Axon if it affects enquiries, email, payment, DNS, security, customer data or operations.\n\n5. Best next step\nSend Axon a short explanation, screenshot and link.\n\n${nextStepLinks(p)}`}
  async function askKimi(q,p,o={}){const r=await fetch(endpoint(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,systemPrompt:o.systemPrompt||systemPrompt(p),mode:o.mode||'ask_axon'})});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.message||'Ask Axon AI is temporarily unavailable.');return String(d.reply||d.answer||d.text||'').trim()}
  function isWeakAiReply(r){const t=String(r||'').trim();return t.length<250||!/What this likely means|Best next step|Quick verdict|Axon/i.test(t)}
  function appendPageReferences(r,p){return /Recommended Axon pages to read:/i.test(r)?r:`${r.trim()}\n\n${nextStepLinks(p)}`}
  async function runAsk(q,type,website,box,o={}){if(!q||!box||isAsking)return;const p=o.profile||detectIntent(q);hideSubmitBox();lastQuestion=q;lastReply='';lastType=type;lastWebsite=website||'';isAsking=true;const b=o.triggerButton||null;const old=b?b.textContent:'';if(b){b.disabled=true;b.textContent=type==='AI Website Advisory Review'?'Analyzing...':'Reviewing...'}renderAnswer(box,o.progressMessage||(type==='AI Website Advisory Review'?'Preparing an AI Website Advisory Review...':`Ask Axon is reviewing this as: ${p.label}...`));try{let reply=null;if(!o.websiteReview)reply=templateAnswer(q,p);if(!reply){reply=await askKimi(q,p,{mode:o.websiteReview?'website_audit':'ask_axon',systemPrompt:o.systemPrompt});if(isWeakAiReply(reply))reply=o.websiteReview?websiteFallback(o.scan,p):fallbackAnswer(q,p);reply=appendPageReferences(reply,p)}lastReply=reply;renderAnswer(box,reply);showSubmitBox()}catch(e){const reply=o.websiteReview?websiteFallback(o.scan,p):(templateAnswer(q,p)||fallbackAnswer(q,p));lastReply=reply;renderAnswer(box,`${reply}\n\nNote: The live AI service could not be reached, so Ask Axon prepared a safe advisory response using available checks and common patterns.`);showSubmitBox();console.warn(e)}finally{isAsking=false;if(b){b.disabled=false;b.textContent=old}}}
  async function scanWebsite(url){const r=await fetch(siteCheckEndpoint(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.message||'Unable to run website check.');return d.scan||null}
  function listValue(v){return Array.isArray(v)?v.join(', '):(v||'Not detected')}
  function formatScanSummary(s){if(!s)return 'No live website scan data was available.';const p=s.performance||{};return [`Checked URL: ${s.url||''}`,`Final URL: ${s.finalUrl||s.url||'Not detected'}`,`HTTP status: ${s.status||'Unknown'}`,`HTTPS: ${s.https?'Yes':'No / not confirmed'}`,`Likely platform: ${listValue(s.platform&&s.platform.detected)}`,`Load time clue: ${p.totalTimeMs?p.totalTimeMs+' ms':'Not detected'}`,`Page size: ${p.pageSizeLabel||'Not detected'}`,`Title: ${s.title||'Not detected'}`,`Meta description: ${s.metaDescription||'Not detected'}`,`H1 headings: ${listValue(s.h1)}`,`Canonical: ${s.canonical||'Not detected'}`,`Robots meta: ${s.robotsMeta||'Not detected'}`,`Mobile viewport: ${s.viewport?'Detected':'Not detected'}`,`Schema: ${s.schema?'Detected':'Not detected'}`,`Open Graph: ${s.openGraph?'Detected':'Not detected'}`,`GA4 clue: ${s.ga4Detected?'Detected':'Not detected'}`,`Forms found: ${s.formCount||0}`,`WhatsApp clue: ${s.whatsappDetected?'Detected':'Not detected'}`,`Images: ${p.imageCount??0}`,`Images missing alt text: ${p.imagesMissingAlt??0}`,`Scripts: ${p.scriptCount??0}`,`Internal links: ${p.internalLinkCount??0}`,`External links: ${p.externalLinkCount??0}`,`robots.txt: ${s.robots&&s.robots.exists?'Found':'Not found'}`,`sitemap.xml: ${s.sitemap&&s.sitemap.exists?'Found':'Not found'}`,`llms.txt: ${s.llms&&s.llms.exists?'Found':'Not found'}`,`Visible text sample: ${s.textSample||'Not available'}`].join('\n')}
  function websiteFallback(s,p){const hasTitle=s&&s.title, hasDesc=s&&s.metaDescription, hasH1=s&&Array.isArray(s.h1)&&s.h1.length;return `1. Quick verdict\nI completed a basic public website check. This is not a full technical audit, but it gives useful clues about SEO, AI-search readiness and conversion basics.\n\n2. What looks good\nThe page ${s&&s.loads?'loaded during the check':'may have loading issues during the check'}. HTTPS is ${s&&s.https?'detected':'not clearly confirmed'}. ${hasTitle?'A page title was detected.':'No clear page title was detected.'}\n\n3. What may be weak or missing\n${hasDesc?'A meta description was detected.':'The meta description appears missing or not detected.'} ${hasH1?'A main heading was detected.':'A clear H1 heading was not detected.'} Schema is ${s&&s.schema?'detected':'not detected'}, and llms.txt is ${s&&s.llms&&s.llms.exists?'found':'not found'}.\n\n4. SEO / AEO / AI-search visibility feedback\nThe site should have clear service wording, strong titles, helpful descriptions, schema, sitemap, robots.txt and AI-friendly plain-English content.\n\n5. Website trust and conversion feedback\nCheck whether visitors quickly understand the services, see contact options, submit forms, use WhatsApp and know why they should trust the business.\n\n6. What to fix first\nStart with title, description, H1, service clarity, contact form, sitemap, schema and AI-ready content.\n\n7. When Axon should help\nAsk Axon to review the full site if you need SEO/GEO/AEO, website revamp, tracking, form delivery, hosting, security or AI-search improvements.\n\n${nextStepLinks(p)}`}
  function populateCommonQuestions(){if(!commonSelect)return;if(commonSelect.options.length<=1){commonQuestions.forEach(q=>{const o=document.createElement('option');o.value=q;o.textContent=q;commonSelect.appendChild(o)})}}
  document.getElementById('askAxonForm')?.addEventListener('submit',e=>{e.preventDefault();const b=e.submitter||e.target.querySelector('button[type="submit"]');const q=questionBox?.value.trim()||'';runAsk(q,'Ask Axon request','',resultBox,{triggerButton:b})});
  askSelectedBtn?.addEventListener('click',()=>{const q=commonSelect?.value.trim()||'';if(!q){commonSelect?.focus();return}if(questionBox)questionBox.value=q;runAsk(q,'Ask Axon request','',resultBox,{triggerButton:askSelectedBtn})});
  document.querySelectorAll('[data-example]').forEach(b=>b.addEventListener('click',()=>{if(questionBox)questionBox.value=b.getAttribute('data-example')||'';hideSubmitBox()}));
  document.getElementById('websiteReviewForm')?.addEventListener('submit',async e=>{e.preventDefault();const url=document.getElementById('websiteUrl')?.value.trim()||'';const notes=document.getElementById('websiteNotes')?.value.trim()||'';const box=document.getElementById('websiteReviewResult');const b=e.submitter||e.target.querySelector('button[type="submit"]');if(!box||!url||isAsking)return;let scan=null;renderAnswer(box,'Checking the live website first: status, title, description, headings, mobile tag, schema, sitemap, robots.txt, llms.txt, analytics clues, forms, links and image clues...');try{scan=await scanWebsite(url)}catch(err){console.warn(err)}const profile=axonIntentProfiles.find(i=>i.key==='website_review')||detectIntent(`${notes} ${url}`);const prompt=`AI Website Advisory Review for a business owner.\n\nWebsite URL: ${url}\nClient notes: ${notes||'None'}\n\nBASIC PUBLIC WEBSITE CHECK RESULTS:\n${formatScanSummary(scan)}\n\nPrepare an actual website advisory review using the scan findings. Avoid generic answers. Explain what Axon may need to check further.`;runAsk(prompt,'AI Website Advisory Review',url,box,{websiteReview:true,triggerButton:b,profile,scan,systemPrompt:websiteAuditPrompt(),progressMessage:'Basic website check completed. Ask Axon is preparing the website advisory review using the scan findings...'})});
  submitForm?.addEventListener('submit',async e=>{e.preventDefault();const status=document.getElementById('askSubmitStatus');if(!lastQuestion||!lastReply){if(status){status.textContent='Please ask a question or run the website review first.';status.className='ask-axon-status error'}return}if(status){status.textContent='Sending to Axon Team...';status.className='ask-axon-status'}const payload={name:document.getElementById('askName')?.value.trim()||'',email:document.getElementById('askEmail')?.value.trim()||'',phone:document.getElementById('askPhone')?.value.trim()||'',company:document.getElementById('askCompany')?.value.trim()||'',website:lastWebsite,requestType:lastType,question:lastQuestion,advisorReply:lastReply};try{const r=await fetch('ask-axon-submit.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw new Error(d.message||'Unable to send right now.');if(status){status.textContent='Sent successfully. A copy has also been emailed to you.';status.classList.add('success')}e.target.reset()}catch(err){if(status){status.textContent=err.message||'Unable to send right now. Please email support@axon.com.sg.';status.classList.add('error')}}});
  populateCommonQuestions();
  if(resultBox&&resultBox.textContent.includes('Your Ask Axon response'))resultBox.textContent='No technical knowledge needed. Type your issue in your own words. Ask Axon will explain what it likely means, what to check first, and when Axon should assist.';
  hideSubmitBox();
})();
